### ISSUE TITLE
Missing setters on Item and Rarity

### ISSUE THREAD

**Issue by BeezBeez** [x0jony/Blackout#1]
Hello ! Thanks for your plugin first of all.
I've noticed the `set` properties are missing in Item and Rarity in the Config file. Thus disabling us to change their values in the config file of EXILED.

Can you do something for this ?

Thanks !

**Comment by x0jony** [comment]
Thank you so much for supporting my work and reporting this mistake to me, I'll merge the pull request now.

I'll be home in about a few hours and build the project.

**Comment by x0jony** [comment]
I've released a new version of the plugin. Thank you so much. I will be closing this issue.
